### ISSUE TITLE
Problems compiling the document, womp womp

### ISSUE THREAD

**Issue by lmwalkowicz** [LSSTScienceCollaborations/ObservingStrategy#98] opened 2015-08-21 23:51 UTC
So @ebellm and I are both having issues (ha HA) compiling the document after making changes-- we think these are just compatibility problems between our LaTeX installation and @drphilmarshall's, but are hesitant to push changes on the off chance these problems originate in the meatware between the keyboard and the chair. What is our best course of action, @drphilmarshall?

**Comment by StephenRidgway** [comment] 2015-08-21 23:55
I found that sometimes I could not compile my changes locally until I deleted my local .pdf thus forcing the recompile. Probably an unnecessary work around if I did things right.

**Comment by drphilmarshall** [comment] 2015-08-22 01:08
I regularly do 

    make clean ; make

which seems to make things work better. If this doesn't work for you let us know, otherwise feel free to close this!

**Comment by ebellm** [comment] 2015-08-22 05:33
`make clean; make` doesn't help me any, but I'm using an old TeXLive installation that I should try updating to see if it helps.

**Comment by drphilmarshall** [comment] 2015-08-22 05:59
Yeah, that could well be it. Someone else was having similar problems (it
was teh KOMA-script version I think), and reached the same conclusion...
Thanks!

**Comment by ebellm** [comment] 2015-08-22 16:41
Okay, I've updated my LaTeX to the latest and greatest of everything, and I'm still having problems.  I think the issue is that the komascript package versions included in this repository are out of date.  If I delete them and use the updated versions in my TeXLive distro, I can compile fine.

Here's LaTeX's noisy error dump:

teresa:whitepaper ebellm$ make
pdflatex LSST_Observing_Strategy_White_Paper.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./LSST_Observing_Strategy_White_Paper.tex
LaTeX2e <2015/01/01> patch level 2
Babel <3.9m> and hyphenation patterns for 79 languages loaded.
(./scrbook.cls
Document Class: scrbook 2013/12/19 v3.12 KOMA-Script document class (book)
(./scrkbase.sty
(/usr/local/texlive/2015/texmf-dist/tex/latex/koma-script/scrbase.sty

LaTeX Warning: \KOMAScriptVersion  is `2013/12/19 v3.12 KOMA-Script',
               but `2015/07/02 v3.18 KOMA-Script' was expected!
               You should not use classes, packages or files from
               different KOMA-Script versions.

(/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/keyval.sty)
(./scrlfile.sty
Package scrlfile, 2013/12/19 v3.12 KOMA-Script package (loading files)
                  Copyright (C) Markus Kohm

)

LaTeX Warning: You have requested, on input line 394, version
               `2015/07/02 v3.18 KOMA-Script ' of package scrlfile,
               but only version
               `2013/12/19 v3.12 KOMA-Script package (loading files)'
               is available.

)) (./tocbasic.sty)

Class scrbook Warning: You've used obsolete option `cleardoubleempty'.
(scrbook)              Usage of this option indicates an old document and
(scrbook)              is deprecated.
(scrbook)              You should simply replace
(scrbook)              usage of option `cleardoubleempty' by `cleardoublepage=e
mpty'.

(/usr/local/texlive/2015/texmf-dist/tex/latex/koma-script/scrsize11pt.clo

LaTeX Warning: \KOMAScriptVersion  is `2013/12/19 v3.12 KOMA-Script',
               but `2015/07/02 v3.18 KOMA-Script' was expected!
               You should not use classes, packages or files from
               different KOMA-Script versions.

) (/usr/local/texlive/2015/texmf-dist/tex/latex/koma-script/typearea.sty

LaTeX Warning: \KOMAScriptVersion  is `2013/12/19 v3.12 KOMA-Script',
               but `2015/07/02 v3.18 KOMA-Script' was expected!
               You should not use classes, packages or files from
               different KOMA-Script versions.

Package typearea, 2015/07/02 v3.18 KOMA-Script package (type area)
                  Copyright (C) Frank Neukam, 1992-1994
                  Copyright (C) Markus Kohm, 1994-

! Undefined control sequence.
l.341 \KOMA@kav@xadd
                    {.typearea.\scr@pkgextension}{twoside}{%

**Comment by lmwalkowicz** [comment] 2015-08-22 17:04
haHA @drphilmarshall you are out of date! @ebellm can you be more specific as to what you deleted? the mention of it in the style file or..?
This doesn't seem like a good long term solution, though...

**Comment by ebellm** [comment] 2015-08-22 17:09
I deleted scrbook.cls   scrkbase.sty  scrlfile.sty

**Comment by lmwalkowicz** [comment] 2015-08-22 17:16
Hm, that doesn't fix it for me :( the TOC and internal hyperlinks are still broken.

**Comment by ebellm** [comment] 2015-08-22 17:18
did you try make clean; make ?

**Comment by lmwalkowicz** [comment] 2015-08-22 17:23
@ebellm yup.

**Closed** 2015-11-12 01:01 UTC
Labels: Bremerton Hack Day!, feedback, latex

**Comment by drphilmarshall** [comment] 2015-11-12 01:04
Alright!  I removed the files below - hopefully this does not break everyone's build. If it does, I guess they'll have to update their TeX distributions...
```
scrbook.cls
scrkbase.sty
scrlfile.sty
tocbasic.sty
tocstyle.sty
```
Thanks for catching this, @ebellm and @lmwalkowicz !

**Comment by ebellm** [comment] 2015-11-12 01:23
Great!  The latest master compiles fine on my system now.
