### ISSUE TITLE
Photo-z's aided by LSST filter gradients

### ISSUE THREAD

**Issue by yoachim** [LSSTScienceCollaborations/ObservingStrategy#128] opened 2015-08-22 17:09 UTC
One of my crazy ideas is that since there will probably be gradients in the filter bandpass shape, one could make a coadded image from the inner chips, and a coadd from outer chips. Doing a difference image of these coadds will effectively generate a narrow-band image. 

People convinced me that this is fun enough that it might find a home in the white paper.

**Comment by ivezic** [comment] 2015-08-22 18:26
This is a great idea! And it will be a very useful test of photometric 
calibration. Do you have any metric in mind?

**Comment by yoachim** [comment] 2015-08-23 04:03
I was thinking of computing the coadd m5 for the chips, doing a sanity check that there would be plenty of galaxies at the right redshift to have a bright emission line in the filter edge. Maybe look at the power spectrum with dithering on vs off, show that with dithering we should be able to detect an all-sky BAO measurement in a narrow redshift range.

**Comment by janewman-pitt-edu** [comment] 2015-09-11 19:39
I've argued a number of times in the past for making it straightforward to grab the effective wavelength/passband for each visit's photometry along with the photometry itself, as this provides effectively some low-resolution spectral information (there are other things than position in the focal plane that change effective throughput curves, e.g. atmospheric transmission variation).  That should capture this information.

**Comment by rhiannonlynne** [comment] 2015-09-11 19:58
Indeed, the plan is to provide a way to access the system response as a function of wavelength along with the photometry for each object (this is actually necessary to get photometry to very high precision for some objects with unusual SEDs). 

In our simulations, we see that the atmosphere transmission variations do change the overall transmission, as does the hardware dependent effects that generally translate as 'position in the focal plane', but that the atmospheric variations generally have a smaller wavelength-dependent effect than the hardware-dependent effects.

**Comment by ivezic** [comment] 2015-09-11 22:26
As Lynne said, the system (atmo + hw) bandpass will be provided for each 
photometric measurement, per explicit SRD requirement (see Section 3.3.4).

**Comment by drphilmarshall** [comment] 2015-11-12 02:51
Assigning @egawiser so he can keep an eye on this. While I agree that it is most cool to think about ways to get more information about the photo-zs from the details of the LSST observing system, those thoughts will only be meaningful if they are quantified in a cosmological accuracy figure of merit. Can you see a route to such a metric? At first it need only be very approximate...

**Comment by janewman-pitt-edu** [comment] 2015-11-12 03:09
Let's see...  The problem is that the aided resolution is partially counteracted by degraded S/N per band. 

 I think we could write down a toy model (that you're trying to centroid a feature; error on centroid goes as (FWHM)/S/N typically).  If we're effectively getting a spectrum with resolution R (i.e. splitting the light into R bins), FWHM is propto 1/R; and effective exposure time per resolution element goes as 1/R, so S/N is propto t^1/2 propto R^(-1/2).  So in net, sigma_z is propto R^(-1/2). 

The result: With 6 effective bins instead of 5, photo-z errors are 9% smaller.  That's probably ~the best case scenario.  That'd have a tiny effect on WL, more significant for BAO, and intermediate for the combination of the two (you can read off an old plot of Hu Zhan's for the FoM from each or in combination as a function of sigma_z).

**Comment by drphilmarshall** [comment] 2016-04-28 18:39
Punting this to the Tucson 2016 milestone, following inactivity on photo-zs more generally ( #198 ). Let's not forget this good idea, though! :-)

**Comment by yoachim** [comment] 2016-04-28 19:40
I did actually play with this and ran some SDSS galaxy spectra through LSST shifted and unshifted filters.  I think my conclusion was that the shift has to be rather large for there to be a clear peak when emission lines are in the shift region:
https://github.com/yoachim/ScratchStuff/blob/master/filter_shift_photo_z/filter_shift_photo_z.ipynb

**Comment by janewman-pitt-edu** [comment] 2016-04-28 19:54
As you go to higher z, lower-metallicity, high-EW galaxies will become more prominent (equivalent widths of 500-1000 angstroms aren't unheard of).  I would expect those aren't included in your SDSS sample?

**Comment by yoachim** [comment] 2016-04-28 20:08
yeah, I just grabbed "elliptical", "starforming", and "starburst" spectra. If you have a spectrum, I can drop it in and see what happens at high redshift. I did make a note that the OII emission line will pass though the filter shift region around z=1.

**Comment by janewman-pitt-edu** [comment] 2016-04-28 20:36
I don't have a spectrum directly, unfortunately.

**Comment by egawiser** [comment] 2021-07-02 11:52
Closing this ancient issue, although the idea is worth revisiting now that we know the final focal plane arrangement, since this will depend on CCD QE as well as filter gradients.

**Closed by egawiser** 2021-07-02 11:52 UTC
Labels: Bremerton Hack Day!, Cosmology, MAF
